services:
  scanpi:
    # build: .
    image: ghcr.io/ksmarty/scanpi:feature-v2
    container_name: scanpi
    ports:
      - "5123:5123"
    volumes:
      - ./scans:/scans
    # environment:
    #   - DEBUG=False
    #   - ROOT_PATH=/
    #   - SCAN_DIRECTORY=/scans
    #   - SOURCES=ADF Front,ADF Back,ADF Duplex
    #   - MODES=Lineart,Halftone,Gray,Color
    #   - RESOLUTIONS=50,100,150,200,250,300,350,400,450,500,550,600
    #   - DATE_FORMAT=%Y-%m-%d-%H-%M-%S
    devices:
      - /dev/bus/usb:/dev/bus/usb
    restart: unless-stopped